//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niflaot_MiTorahtecha.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niflaot_MiTorahtecha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א:א, וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְּמִדְבַּר סִינַי, בְּאֹהֶל מוֹעֵד: בְּאֶחָד לַחֹדֶשׁ הַשֵּׁנִי בַּשָּׁנָה הַשֵּׁנִית, לְצֵאתָם מֵאֶרֶץ מִצְרַיִם--לֵאמֹר
        ///א:ב, שְׂאוּ, אֶת-רֹאשׁ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל, לְמִשְׁפְּחֹתָם, לְבֵית אֲבֹתָם--בְּמִסְפַּר שֵׁמוֹת, כָּל-זָכָר לְגֻלְגְּלֹתָם
        ///א:ג, מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה, כָּל-יֹצֵא צָבָא בְּיִשְׂרָאֵל--תִּפְקְדוּ אֹתָם לְצִבְאֹתָם, אַתָּה וְאַהֲרֹן
        ///א:ד, וְאִתְּכֶם יִהְיוּ, אִישׁ אִישׁ לַמַּטֶּה--אִישׁ רֹאשׁ לְבֵית-אֲבֹתָיו, הוּא
        ///א:ה, וְאֵלֶּה שְׁמוֹת [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bamidbar {
            get {
                return ResourceManager.GetString("bamidbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א:א, בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ.
        ///א:ב, וְהָאָרֶץ, הָיְתָה תֹהוּ וָבֹהוּ, וְחֹשֶׁךְ, עַל-פְּנֵי תְהוֹם; וְרוּחַ אֱלֹהִים, מְרַחֶפֶת עַל-פְּנֵי הַמָּיִם.
        ///א:ג, וַיֹּאמֶר אֱלֹהִים, יְהִי אוֹר; וַיְהִי`-אוֹר.
        ///א:ד, וַיַּרְא אֱלֹהִים אֶת-הָאוֹר, כִּי-טוֹב; וַיַּבְדֵּל אֱלֹהִים, בֵּין הָאוֹר וּבֵין הַחֹשֶׁךְ.
        ///א:ה, וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם, וְלַחֹשֶׁךְ קָרָא לָיְלָה; וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם אֶחָד.
        ///א:ו, וַיֹּאמֶר אֱלֹהִים, יְהִי רָקִיעַ בְּתוֹךְ הַמָּיִם, וִיהִי מַבְד [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bereshis {
            get {
                return ResourceManager.GetString("bereshis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א:א, אֵלֶּה הַדְּבָרִים, אֲשֶׁר דִּבֶּר מֹשֶׁה אֶל-כָּל-יִשְׂרָאֵל, בְּעֵבֶר, הַיַּרְדֵּן: בַּמִּדְבָּר בָּעֲרָבָה מוֹל סוּף בֵּין-פָּארָן וּבֵין-תֹּפֶל, וְלָבָן וַחֲצֵרֹת--וְדִי זָהָב.
        ///א:ב, אַחַד עָשָׂר יוֹם מֵחֹרֵב, דֶּרֶךְ הַר-שֵׂעִיר, עַד, קָדֵשׁ בַּרְנֵעַ.
        ///א:ג, וַיְהִי בְּאַרְבָּעִים שָׁנָה, בְּעַשְׁתֵּי-עָשָׂר חֹדֶשׁ בְּאֶחָד לַחֹדֶשׁ; דִּבֶּר מֹשֶׁה, אֶל-בְּנֵי יִשְׂרָאֵל, כְּכֹל אֲשֶׁר צִוָּה יְהוָה אֹתוֹ, אֲלֵהֶם.
        ///א:ד, אַחֲרֵי הַכֹּתוֹ, אֵת סִיחֹן מֶלֶךְ הָאֱמֹרִי, אֲשֶׁר יוֹשֵׁב, בְּחֶשְׁבּוֹן--וְ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string devarim {
            get {
                return ResourceManager.GetString("devarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א:א, וְאֵלֶּה, שְׁמוֹת בְּנֵי יִשְׂרָאֵל, הַבָּאִים, מִצְרָיְמָה: אֵת יַעֲקֹב, אִישׁ וּבֵיתוֹ בָּאוּ.
        ///א:ב, רְאוּבֵן שִׁמְעוֹן, לֵוִי וִיהוּדָה.
        ///א:ג, יִשָּׂשכָר זְבוּלֻן, וּבִנְיָמִן.
        ///א:ד, דָּן וְנַפְתָּלִי, גָּד וְאָשֵׁר.
        ///א:ה, וַיְהִי, כָּל-נֶפֶשׁ יֹצְאֵי יֶרֶךְ-יַעֲקֹב--שִׁבְעִים נָפֶשׁ; וְיוֹסֵף, הָיָה בְמִצְרָיִם.
        ///א:ו, וַיָּמָת יוֹסֵף וְכָל-אֶחָיו, וְכֹל הַדּוֹר הַהוּא.
        ///א:ז, וּבְנֵי יִשְׂרָאֵל, פָּרוּ וַיִּשְׁרְצוּ וַיִּרְבּוּ וַיַּעַצְמוּ--בִּמְאֹד מְאֹד; וַתִּמָּלֵא הָאָרֶץ, אֹתָם.
        ///א:ח, וַיָּקָם מֶלֶךְ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shemot {
            get {
                return ResourceManager.GetString("shemot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א:א, וַיִּקְרָא, אֶל-מֹשֶׁה; וַיְדַבֵּר יְהוָה אֵלָיו, מֵאֹהֶל מוֹעֵד לֵאמֹר.
        ///א:ב, דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל, וְאָמַרְתָּ אֲלֵהֶם, אָדָם כִּי-יַקְרִיב מִכֶּם קָרְבָּן, לַיהוָה--מִן-הַבְּהֵמָה, מִן-הַבָּקָר וּמִן-הַצֹּאן, תַּקְרִיבוּ, אֶת-קָרְבַּנְכֶם.
        ///א:ג, אִם-עֹלָה קָרְבָּנוֹ מִן-הַבָּקָר, זָכָר תָּמִים יַקְרִיבֶנּוּ; אֶל-פֶּתַח אֹהֶל מוֹעֵד, יַקְרִיב אֹתוֹ, לִרְצֹנוֹ, לִפְנֵי יְהוָה.
        ///א:ד, וְסָמַךְ יָדוֹ, עַל רֹאשׁ הָעֹלָה; וְנִרְצָה לוֹ, לְכַפֵּר עָלָיו.
        ///א:ה, וְשָׁחַט אֶת-בֶּן הַבָּקָר, לִפְנֵי יְהוָה [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vayikra {
            get {
                return ResourceManager.GetString("vayikra", resourceCulture);
            }
        }
    }
}
